apiVersion: apps/v1
kind: Deployment
metadata:
  name: chitti-deployment
  labels:
    app: chitti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chitti
  template:
    metadata:
      labels:
        app: chitti
    spec:
      containers:
      - name: chitti-container
        image: varsha0411/chitti:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chitti-service
spec:
  selector:
    app: chitti
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
